# docker-compose.yml
version: "3.8"

services:
  moongchi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moongchi-backend
    ports:
      - "8080:8080"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - moongchi-backend
    restart: always