services:
  moongchi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moongchi-backend
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always